version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    # ตั้งค่าโซนเวลา + กำหนด default-time-zone ให้ MySQL ตั้งแต่บูต
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    command: >
      --default-authentication-plugin=mysql_native_password
      --default-time-zone=+07:00
    ports:
      - "8830:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # (ทางเลือก) ใส่ my.cnf ถาวรของมึงเอง ถ้าจะคอนฟิกอื่น ๆ เพิ่ม
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - weblab830
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      TZ: Asia/Bangkok                 # ให้ container ใช้เวลาประเทศไทย
      PHP_DATE_TIMEZONE: Asia/Bangkok  # เวลาใน PHP/phpMyAdmin เป็นไทยด้วย
    ports:
      - "8831:80"
    depends_on:
      - db
    networks:
      - weblab830
    restart: always

networks:
  weblab830:
    driver: bridge

volumes:
  mysql_data:
    driver: local
